### ISSUE TITLE
Where do I put this?

### ISSUE THREAD

**Issue by crearo** [ryanpepper/circleci-cmake-now#1]
I'm pretty new to circleci's yml files and I don't quite know where/how to use this file.

```version: 2.0
   2   │ 
   3   │ jobs:
   4   │   build_cpp:
   5   │     machine:
   6   │       timezone:
   7   │         Europe/Vilnius
   8   │       environment:
   9   │         PATH: "/home/ubuntu/cmake-3.10.2-Linux-x86_64/bin:$PATH"
  10   │ 
  11   │     dependencies:
  12   │       cache_directories:
  13   │         - ~/cmake-3.10.2-Linux-x86_64
  14   │       override:
  15   │         - >
  16   │           if [ ! -d ~/cmake-3.10.2-Linux-x86_64 ]; then
  17   │             echo "No cache - building CMake"
  18   │             cd ~ && wget --quiet https://cmake.org/files/v3.10/cm
       │ ake-3.10.2-Linux-x86_64.tar.gz && tar -xvf cmake-3.10.2-Linux-x86
       │ _64.tar.gz
  19   │           else
  20   │             echo "Cached CMake found"
  21   │           fi
  22   │     docker:
  23   │       - image: gcc:7
  24   │     steps:
  25   │       - checkout
  26   │       - run: ./build.sh
  27   │ 
  28   │ workflows:
  29   │   version: 2
  30   │   build_and_test:
  31   │     jobs:
  32   │       - build_cpp```

Is what my config file looks like, but this fails because circleci can't have both a machine and a docker image. What do I do?

**Comment by crearo** [comment]
Okay. I figured this repo was made for circleci 1.

I've updated it to work:
```
version: 2.0

jobs:
  build_cpp:
    docker:
      - image: gcc:7
    steps:
      - checkout
      - run:
          name: "Find or Download CMake"
          command: |
            if [ ! -d ~/cmake-3.10.2-Linux-x86_64 ]; then
              echo "No cache - building CMake"
              cd ~ && wget --quiet https://cmake.org/files/v3.10/cmake-3.10.2-Linux-x86_64.tar.gz && tar -xvf cmake-3.10.2-Linux-x86_64.tar.gz
            else
              echo "Cached CMake found"
            fi
      - run:
          name: "Add environment variables"
          command: |
            echo 'export PATH=~/cmake-3.10.2-Linux-x86_64/bin:$PATH' >> $BASH_ENV
            source ~/.bashrc
      - run: ./build.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_cpp
```

I'm still not sure if this is the best way to do it.
